// scripts/generate-content.js
// Reads markdown files at build time and generates TypeScript modules
const fs = require('fs').promises;
const path = require('path');
const matter = require('gray-matter');

async function generateArticles() {
  const articlesDir = path.join(__dirname, '..', 'articles');
  const outFile = path.join(__dirname, '..', 'src', 'generated', 'articles.ts');
  
  const files = await fs.readdir(articlesDir);
  const articles = [];
  
  for (const fileName of files.filter(f => f.endsWith('.md'))) {
    const id = fileName.replace(/\.md$/, '');
    const fullPath = path.join(articlesDir, fileName);
    const fileContents = await fs.readFile(fullPath, 'utf8');
    const matterResult = matter(fileContents);
    
    articles.push({
      id,
      title: matterResult.data.title,
      date: matterResult.data.date,
      category: matterResult.data.category,
      published: matterResult.data.published === true || matterResult.data.published === 'true',
      content: matterResult.content,
    });
  }
  
  const output = `// Auto-generated by scripts/generate-content.js
// DO NOT EDIT MANUALLY

export interface ArticleData {
  id: string;
  title: string;
  date: string;
  category: string;
  published: boolean;
  content: string;
}

export const articles: ArticleData[] = ${JSON.stringify(articles, null, 2)};

export default articles;
`;
  
  await fs.mkdir(path.dirname(outFile), { recursive: true });
  await fs.writeFile(outFile, output, 'utf8');
  console.log(`✓ Generated ${articles.length} articles → src/generated/articles.ts`);
}

async function generateQuotes() {
  const quotesPath = path.join(__dirname, '..', 'quotes', 'quotes.md');
  const outFile = path.join(__dirname, '..', 'src', 'generated', 'quotes.ts');
  
  const fileContents = await fs.readFile(quotesPath, 'utf8');
  
  const output = `// Auto-generated by scripts/generate-content.js
// DO NOT EDIT MANUALLY

export const quotesMarkdown = ${JSON.stringify(fileContents)};

export default quotesMarkdown;
`;
  
  await fs.mkdir(path.dirname(outFile), { recursive: true });
  await fs.writeFile(outFile, output, 'utf8');
  console.log(`✓ Generated quotes → src/generated/quotes.ts`);
}

async function main() {
  try {
    await generateArticles();
    await generateQuotes();
    console.log('✓ Content generation complete');
  } catch (err) {
    console.error('✗ Error generating content:', err);
    process.exit(1);
  }
}

main();
